@startuml
package ユーザ集約 {
object ユーザー {
    名前
    メールアドレス
    パスワード
    スキル
    年数
    自己紹介
    経歴
    }
    note bottom of ユーザー
必須
- 名前: 255文字以内(ユニーク)
- メールアドレス: 255文字以内
- パスワード: 12文字以上,英数字それぞれ最低1文字以上
- スキル
    - タグ名(選択式)
    - 評価: 1~5
    - 1つ以上
任意項目
- 年数: ０以上のint型(5年まで)
- 自己紹介: 2000字以内
- 経歴
    - 詳細: 1000字以内
    - 西暦from: 1970年以上のint型
    - 西暦to: 1970年以上のint型、西暦fromよりも大きい数字
    end note
object タグ {
    ID
    タグ名
    評価
    年数
    }
    users -{ chats

  }


@enduml